### ISSUE TITLE
Response headers don't appear

### ISSUE THREAD

**Issue by pacohernandezg** [mulesoft/api-console#115]
Hello.

I think there is a bug showing response headers.

I have the following definition:
/user:
&nbsp;&nbsp;options:
&nbsp;&nbsp;&nbsp;&nbsp;responses:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;200:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;headers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Allow:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;description: Allowed methods
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: string

If I invoke the options verb on the resource with Postman, the response headers appear (Allow and CORS related ones): 

![screen shot 2015-03-09 at 10 57 12](https://cloud.githubusercontent.com/assets/2727545/6552972/ec8c7bae-c64b-11e4-8c55-ee37df17d33d.png)

But if I invoke the same verb on the resource with RAML API-Console, the response headers do not appear.

![screen shot 2015-03-09 at 10 57 03](https://cloud.githubusercontent.com/assets/2727545/6552985/1640c6da-c64c-11e4-885d-353eb9e55bcd.png)

Thank you very much.

Best regards,
Paco Hernández.

**Comment by blakeembrey** [comment]
@pacohernandezg It looks like this making CORS requests to your local API? With CORS, the headers aren't exposed to the browser by default. You're server will need to send back a `Access-Control-Expose-Headers` header. Postman works because they have a higher level API access in the browser (it's a plugin) than a normal web page.
