### ISSUE TITLE
Problem deploying the api-console with a fixed RAML as source

### ISSUE THREAD

**Issue by mickeyl** [mulesoft/api-console#126]
Hi,

I'm trying to use your documentation to deploy the api-console with a fixed RAML. Unfortunately, everytime I try I get a JS error like:

ReferenceError: Can't find variable: RAML

I'm using <raml-console src="<path-to-my-.raml">

What am I missing?

**Comment by jcenturion** [comment]
@mickeyl: you have to include ```api-console.js``` and ```api-console-vendor.js```. I think the second one is missing on you deployment. I will fix the documentation.

**Comment by zkilgore** [comment]
I am having this problem as well, and when I inspect `api-console-vendor.js`, the file is blank. Any idea what is going on there?

**Comment by jcenturion** [comment]
@zkilgore: Could you try the following steps?

1. Install Sass - gem install sass (not needed if you already have sass installed)
2. Install grunt-cli globally - npm install -g grunt-cli
3. Install bower globally - npm install -g bower
4. Install the console's NPM packages - `npm install`
5. Install the console's Bower packages - `bower install`
6. Run `grunt build`

Thanks,
Javier.

**Comment by zkilgore** [comment]
Hey Javier,

Thanks for the quick response. Ran those exact steps and still nothing.

Also, `grunt server` isn't actually defined in the grunt file, but just
running `grunt` starts up the server. However due to the
`api-console-vendor.js` file being empty I'm getting a bunch of js errors
like

```Uncaught ReferenceError: RAML is not defined
Uncaught ReferenceError: $ is not defined```

when I check it out in the browser.

Any other dependencies I'm missing possibly? I don't regularly use angular
so maybe something with that versioning?

On Tue, Apr 21, 2015 at 11:24 AM Javier <notifications@github.com> wrote:

> @zkilgore <https://github.com/zkilgore>: Could you try the following
> steps?
>
>    1. Install Sass - gem install sass (not needed if you already have
>    sass installed)
>    2. Install grunt-cli globally - npm install -g grunt-cli
>    3. Install bower globally - npm install -g bower
>    4. Install the console's NPM packages - npm install
>    5. Install the console's Bower packages - bower install
>    6. Run grunt build
>
> Thanks,
> Javier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mulesoft/api-console/issues/126#issuecomment-94838020>
> .
>

**Comment by zkilgore** [comment]
Hey Javier,

Thanks for the quick response. Ran those exact steps and still nothing.

Also, `grunt server` isn't actually defined in the grunt file, but just running `grunt` starts up the server. However due to the `api-console-vendor.js` file being empty I'm getting a bunch of js errors like 

    Uncaught ReferenceError: RAML is not defined
    Uncaught ReferenceError: $ is not defined

when I check it out in the browser.

Any other dependencies I'm missing possibly? I don't regularly use angular so maybe something with that versioning?

**Comment by jcenturion** [comment]
@zkilgore:

After running `bower install`, your bower_components folder should looks like:

![screen shot 2015-04-28 at 10 01 23 am](https://cloud.githubusercontent.com/assets/302314/7370048/967ba212-ed8d-11e4-8398-c9dae5bc01ea.png)

If not, you have a local issue with bower.

On the other hand, the folder `/dist` has the api-console compiled so you can use it directly.

Regards,
Javier.

**Comment by inmzkhan01** [comment]
Any update ? I am facing this issue, please help.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
