### ISSUE TITLE
Populate Type Examples in URI Parameters of Try it

### ISSUE THREAD

**Issue by ibnesayeed** [mulesoft/api-console#281]
``` yaml
#%RAML 1.0
title: Programming Language Populariy
version: 1
baseUri: http://example.com
types: 
  language:
    type: string
    description: A programming language name
    enum: [Ruby, Python, JavaScript]
  country:
    type: string
    description: A country name
    examples:
      oneword: Canada
      acronym: USA
      withspace: United Kingdom
/popularity/{lang}/{place}/{year}:
  description: Yearly populaity of a language in a geographical region
  uriParameters:
    lang:
      type: language
    place:
      type: country
    year:
      type: number
      description: Year
      examples:
        earliest: 2000
        latest: 2015
  get:
    responses:
      200:
        body:
          application/json:
            example: {"lang": "Ruby", "place": "USA", "popularity": "High"}
```

The above code, when loaded in the api-console, does not meet the following expectation (or my wish list):
- [x] The `Types` block should show examples under the description of each `type` entry and the same should be available in the overlay tooltip that appears when a defined `type` name is clicked under URI parameter listing
- [x] The examples should also be shown in the URI parameter listing for the parameters that are defined inline (in this case, the `year` parameter)
- [x] Try it block's URI parameters section should load examples given in the `type` definition, such as a dropdown selection for `lang` parameter
- [ ] When more than one examples are provided (inline like `year` or in the `type` definition like `place:country`), the Try it URI parameters should allow user selection (currently it only allows using the first example) along with the free-form entry

**Comment by sichvoge** [comment]
Very good point you making here! Thanks!

**Comment by sichvoge** [comment]
With v4, we at least have done the first and the third. I checked both. Still, the others are open.

**Comment by jarrodek** [comment]
One note here - dropdown list with suggestion is rendered only it the type of the property is enum / boolean. Otherwise it renders text field only and there's not way of selecting preexisting values.
In the later case example values could be listed in inline documentation for a query / uri parameter from where the user could copy / paste the value. It also could be listed with a button to replace the value in the input.

Thant is all I can offer here.

**Comment by ibnesayeed** [comment]
@jarrodek another way to deal with it is to use a combo-box component that allows user to select values from a dropdown list which is pre-populated based on examples, but at also allows free-form text entry. This is the kind of input that is used in search suggestion implementations sometimes.

**Comment by ibnesayeed** [comment]
Along the same lines, [Datalist Element](http://caniuse.com/#search=datalist) can be used for the purpose as combo-box is not native to browsers, but this one is.

**Comment by jarrodek** [comment]
@ibnesayeed I'm aware of that solution but I don't want to add another component to the console which already grown big. I was considering this before for different purpose but because it would require adding more code I resigned from using this solution.
I am investigating use of `datalist` element but because it can't be styled it might not be appropriate to use it giving current design.

**Comment by jarrodek** [comment]
The remaining item on the list won't be supported. Examples are only rendered in the documentation. They are not used to build the request.
