### ISSUE TITLE
'Try It' security scheme Pass Through support.

### ISSUE THREAD

**Issue by zaibon** [mulesoft/api-console#293]
I have the following security scheme :

``` raml
securedBy: [ JWT ]
securitySchemes:
    JWT:
        type: Pass Through
        description:
            This API uses JWT to authenticate the requests.
        describedBy:
          headers:
            Authorization:
              description: |
                Should contain the JWT token.
                Format of the value is : bearer $JWT_TOKEN
          responses:
            401:
              description: Unauthorized
```

When trying to use 'Try it' I have this error message:
`Custom Security Schemes are not supported in Try It`

Isn't Pass Through supposed to be a built-in security scheme ?
I'm using RAML 1.0.

**Comment by sichvoge** [comment]
Thanks for raising the issue. We will investigate whats the exact problem is.

**Comment by sichvoge** [comment]
That might failing since "Pass Through" is not part in here: https://github.com/mulesoft/api-console/blob/adb773b7eca66881772618293080e48f25a85c15/src/common/client/auth_strategies.js#L10 or https://github.com/mulesoft/api-console/blob/e4ada89b3552d6446e7ac472ff33c95a22202740/dist/scripts/api-console.js#L3043. although I don't understand why there is the same code two times.

**Comment by carobazan** [comment]
verified on QA branch, will be included in next release
