### ISSUE TITLE
Please push 3.0.5 and 3.0.6 tags on npm

### ISSUE THREAD

**Issue by malavbhavsar** [mulesoft/api-console#319]
Latest available on npm is 3.0.4. Thanks!

**Comment by malavbhavsar** [comment]
Hi @sichvoge, could you please explain why is this wontfix? We use api-console and other mulesoft services in production and would love to get new updates as they become available.

**Comment by sichvoge** [comment]
Its a `wontfix` since there is nothing to fix. I am currently trying to categorize the current issues to have a better overview what needs to be done actively by our development team from an implementation perspective.

Anyways, I agree that we should publish a new version to npm and we will do that.

**Comment by nmarinel01** [comment]
3.0.11 tag is available
Regards
