### ISSUE TITLE
Use local file url as raml src

### ISSUE THREAD

**Issue by coltonlw** [mulesoft/api-console#330]
Hi,

Is it possible to use a local file url as a src to RAML?  When loading the console from a file:// url, the console and styles load but if src is set to either a relative uri or an absolute uri beginning with file://, I get an error "Cannot read property 'buffer' of undefined"

**Comment by frisco82** [comment]
It is not working, the error has no relation with the real error as it tries to parse the parser error and it fails. The real error is that file could not be located even when the path is correct due to incorrect path manipulation on "Project.unitAsync" file:// are not considered as absolute paths and the process ends with an incorrect path like file://pathToApi/file://pathToApi/api.raml

**Comment by sichvoge** [comment]
@coltonlw @friscoMad this should be fixed with v4 and the CLI tools available to generate the console from a local file. Check out the CLI [here](https://github.com/mulesoft-labs/api-console-cli) and the new version [here](https://github.com/mulesoft/api-console/tree/release/4.0.0#build-tools).

**Comment by jarrodek** [comment]
Fixed with https://github.com/mulesoft/api-console/commit/c74eacde58e40d1d79c4885b15fa3ff210b6610c
