### ISSUE TITLE
api-console-vendor.js size is huge

### ISSUE THREAD

**Issue by davidacampos** [mulesoft/api-console#331]
Is it on purpose that from 2.x to 3.x that file size grew from ~3MB to ~19MB? This slows downs a lot the loading.

**Comment by sichvoge** [comment]
I think thats the parser. With the JS parser release 1.1.2 the team significantly reduced the size of the parser from 17mb to 3mb; that should help here in this case as well. We need to do some sanity checks before we bump the version in the console to 1.1.2 since the parser introduced some new functionality.

**Comment by vrenjith** [comment]
I had to put an nginx with `gzip on` to get it to a reasonable loading time.

**Comment by sichvoge** [comment]
@davidacampos @vrenjith is this still a problem?

**Comment by davidacampos** [comment]
Looks a lot better, still not as small, but 4.3MB is better than ~19MB (for the latest release of 3.x). Thanks!

**Comment by jarrodek** [comment]
4.3MB is for unoptimised version of the console. If you use build tools (node module or CLI tool) then it will reduce size to about ~2MB.
We are still working on reducing this number.
