### ISSUE TITLE
Any interest in the ability to pass in a RAML path when the server is started?

### ISSUE THREAD

**Issue by andrewbredow** [mulesoft/api-console#39]
Hey all! I'm relatively new to RAML, but have an idea I'd like to throw out. Currently, the RAML console can be "seeded" with a RAML file by either a query string parameter, form field, or the iframe method.

I have something in mind that could help when using the console _as RAML is being developed_ OR when the console is running on a server for users to view.

In particular, it seems like it would be useful to be able to pass in a path for a RAML file when the server is created. For example, `grunt server --raml=http://mydomain.com/docs.raml` or `grunt server --raml=/some/local/path/docs/raml`. That latter allowing a local file to be easily passed in during development.

Does this fly in the face of other functionality? At first glance, it doesn't appear that there is anything similar in place.

**Comment by mgogov** [comment]
+1 for  @andrewbredow's idea.

We also put our RAML definition of the API alongside the source code to keep docs and code in sync. Our team members code in different editors so while the API designer is pretty cool, people tend to prefer to code in their editors with all their plugins etc, instead of doing it in the browser.

Our dev workflow right now is to run the API console on a dev server and use the raml query string param so we open a URL such as http://api_console_dev_host:9000?raml=raml_file_dev_project:3456/api.raml and refresh this URL while doing changes in the raml file to see the results. This would be easier to do if we had a console option to predefine the raml file location. It'd be also easier to deploy a customer facing console without a query string raml param which might scare non-that-technical people away.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
