### ISSUE TITLE
Build tool never finishes

### ISSUE THREAD

**Issue by stojsavljevic** [mulesoft/api-console#525]
Hi,

I'm trying to build a console (v4) with `api-console-builder` like this:
```
const builder = require('api-console-builder');

builder({
        src: 'bower_components/api-console/', //custom build 
        dest: 'build',
        mainFile: 'index.html',
        verbose: true
    })
    .then(() => {
        console.log('Build complete');
        // run polymer serve build/ --open 
    })
    .catch((cause) => console.log('Build error', cause.message));
```

I have:
```
<nodeVersion>v6.10.1</nodeVersion>
<npmVersion>4.4.4</npmVersion>
```

But build never finishes. Here is the log: 
[build-log.txt](https://github.com/mulesoft/api-console/files/1248062/build-log.txt)

Another problem is that the builder seems to have a problem if the `mainFile` is pointed to as a relative/absolute path.
Only when placing it next to the script it did not explode saying cannot find the index.html file

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.

The `src` property tells where the custom build of the API console is. Not the location of the console downloaded via bower `command`. I'm not sure what you are trying to achieve with this configuration. So according to this configuration the program will:
- use `bower_components/api-console/` as a source of the console
- install bower dependencies in `bower_components/api-console/bower_components`
- use `./index.html` as an entry point to the application (where it looks for imports)
- and output the work to `./build`.

Possibly you may want to skip the `src` property. It should be used if you copied the API console project and want to use this copy to generate the build. Otherwise the tool downloads latest release from github.

Please, let me know if that helps.

**Comment by stojsavljevic** [comment]
Hi,

sorry for the late reply.

I want to create a local distribution of `api-console` with my custom `index.html` that will allow me to open different raml files by sending relative path to raml as request parameter.
With the configuration above I was trying to compress the generated output of `api-console`.

I finally made it work with the following configuration:
```
const builder = require('api-console-builder');

builder({
	src: './',
	dest: 'build',
	mainFile: 'index.html',
	verbose: true
})
.then(() => {
	console.log('Build complete');
	// run polymer serve build/ --open 
})
.catch((cause) => console.log('Build error', cause.message));
```

However, I had issues when trying to place `index.html` in some inner directory (currently, everything is in the root of the project). 
I tried to 2 ways:
* to place above js file in a directory next to `index.html` and call `node path/to/compress.js`
* to set relative path to `index.html` in `mainFile` attribute

But nothing seems to work.
Anyway, this is not a big issue for me so feel free to close this issue.

Thanks!

**Comment by jarrodek** [comment]
The issue that you may have with the build is that the parser is walking through imports and dependency tree so it paths are incorrect the build fails. As long `index.html` and `bower_components` are in the same directory it should work.

If this means I can close the issue?

**Comment by stojsavljevic** [comment]
Thanks for the tip.

Closing this one..
