### ISSUE TITLE
API Console doesn't work if RequireJS is defined

### ISSUE THREAD

**Issue by nescalante** [mulesoft/api-console#531]
As a requirement of an application, RequireJS is previously defined.
The issue is that [raml-js-parser component imports file](https://github.com/advanced-rest-client/raml-js-parser/blob/stage/raml-js-parser-imports.html) tries to load the [RAML Parser web bundle](https://github.com/advanced-rest-client/raml-js-parser/blob/stage/raml-1-parser.js) and that bundle uses [RequireJS if its previously defined](https://github.com/raml-org/raml-js-parser-2/blob/master/src/browserVersionGenerator/browserVersionGenerator.ts#L102), but then the console expects `RAML` as a global, and that is not happening.

Same issue happens with CodeMirror.

Is there something that I can do to solve this issue?

Thanks in advance.

**Comment by jarrodek** [comment]
I'm not sure what I can do to solve this. I'm only consuming the parser in this project. The Exchange doesn't actually have to use this parser. It can use any other instance of the parser. The parser is used separately anyway.

I can alter the parser element to accept a property that is the parser and it would use this object to call `loadApi` and `parseRAML` functions. It could work like this:

```html
<raml-js-parser></raml-js-parser>
<script>
document.querySelector('raml-js-parser').parser = scope.RAML.Parser;
</script>
```
Once set, the parser would use whatever object was passed to the `parser` property instead of global `RAML.Parser` property.

The same for `code-mirror`.

Is this something that would fix this issue? Maybe you can suggest different approach?

**Comment by jarrodek** [comment]
The v4 is no longer supported in this project.
