### ISSUE TITLE
Error when using Raml header element from api console

### ISSUE THREAD

**Issue by HaslesGitHub** [mulesoft/api-console#562]
Hello,

Raml files can contain headers. Like this ex.:

/{cNo}/Products:
description: This is the URL where you can get info to.
type: { errorandvalidationpost }
get:
headers:
x-test-key:
displayName: Test key
description: This header is used to send data that contains your test key
type: string
queryParameters:
productCodes:
displayName: Product codes
type: ProductCodes
description: Product codes
required: false
responses:
200:
body:
application/json:
example: !include schemas/productI.json
type: !include schemas/productI.schema.json

But when I try to set data in the header(x-test-key) from API console (https://github.com/mulesoft/api-console)
I always receive error. from the .net rest service:

The requested URL can’t be reached
The service might be temporarily down or it may have moved permanently to a new web address.
Failed to fetch

What am I doing wrong here? Or is this a bug in the api consol.
Because when I send the request from ex. PostMan with header data It works fine.

I think maybe the custom header is placed in wrong place in the request message.
I see it sends as a OPTIONS not a GET from the console when I set data in the header from the Console.
But I can’t understand why this happings, or if this is the error here.

Regards

Pål Fredrik

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.

This is CORS issue and not console's. The console is a web application and has to follow the same rules as any web app. This includes CORS. When the browser is making a request to a different uri scheme (different scheme, host or port) it sends `OPTIONS` request first to detect if the server accepts connections from your current domain. If yes, then it returns proper headers that tells the browser to make it's request. Because it doesn't make the `GET` request it means that the server does not allow to make a connection form the domain where the console is hosted.

There's no easy workaround for this. For chrome we have an extension that proxy requests without CORS limitations. You see the banner in chrome if the extension is not installed. 
Otherwise, you can setup server proxy and proxy the traffic though it.  
You can find detailed description here: https://github.com/mulesoft/api-console/blob/master/docs/cors.md

I am closing this as WAI.

**Comment by HaslesGitHub** [comment]
Thanks, Just strange the Api consol works fine without added headers (?)

**Comment by HaslesGitHub** [comment]
Thanks it works fine after set the webserver(web.config) to allow a custome header.
