### ISSUE TITLE
Try It with client_credentials doesn't display scopes selection

### ISSUE THREAD

**Issue by CameronGo** [mulesoft/api-console#568]
I'm still using the v3.0.8 api console in production, but trying to move over to the new api console using the new build tools.

The first thing I noticed is that in my old raml my oauth2 authorization grants is listed as:
authorizationGrants: [ credentials ]

When this is the case, I can see the token and authorization endpoints in the api console with a list of the defined scopes, but when I try to use Try It, my JS console tells me:
Uncaught Error: Unknown authorization method credentials

OK, so a little bit of research and I see something has changed in the RAML spec and that now what is expected is client_credentials.  Great, I think that is better as well, so I update my RAML and it now has this:
authorizationGrants: [ client_credentials ]

My API Console is now able to get an oauth2 token; however, now there are no options to select or list the scopes required, so the token I get is always just the default scope assigned from oauth token endpoint.

I've flipped it back and forth and monkeyed with how the scopes are defined, and all of that is correct.

So what is it exactly that is broken here?

**Comment by jarrodek** [comment]
Apparently there is an issue that prohibits setting up scopes when using client credentials grant type.
This is something to be fixed as a major issue.

As my suggestion. We are going to release new version of the console. It's not going to happen this or next week as there's a lot to do in terms of writing documentation for it and updating build tools. 
If that is possible I would suggest to wait a bit because new version is so much cooler :sunglasses:

**Comment by jarrodek** [comment]
This is fixed in next version of the console (5.0). Currently in preview.

**Comment by jarrodek** [comment]
This is fixed in latest release of APIC 5.0.0
