### ISSUE TITLE
Need better refresh and error handling

### ISSUE THREAD

**Issue by DavidBiesack** [mulesoft/api-console#66]
I've cloned this repo and deployed the dist in a Tomcat engine. 
I've found three (serious) usability issues with the single page model.

On the initial screen, I enter the URL of a RAML doc and select [LOAD FROM URL] After exploring it a bit, I go to my (external) editor and update/save the RAML. 

To refresh in the API Console, I cannot use the browser Back button; I must refresh the page. This is very unintuitive as the initial button feels like a submit. Further, when I refresh, the URL field is empty and I have to copy/paste the URL again to refresh. If this worked more like a submit/back, this would be much easier to use.

Also, if there is a syntax error in the RAML, I get back a display of some unformatted JSON with the error message inside it, and this is hard to decipher. It would be better to list the error message and line number, then show the RAML and highlight the error.

Finally, if instead of pasting in a RAML URL, if I paste in full RAML then select [ LOAD RAML] to try it out, again I can't use the browser Back button to return to my RAML source and edit it. If I refresh the page, the RAML source is gone. Again, a Submit/Back user experience would be much better.

[Yes, I know I can use RAML API Designer but its persistence model does not work well with other toolchains, alternate source layouts such as using a schemas/ subdirectory for ll schema files... in fact I can't get it to recognize .xsd schema files   ]

I believe there is another request to allow passing the RAML URL to API Console startup - a query parameter would be very useful if I could refresh to reload.

**Comment by mgogov** [comment]
@DavidBiesack, I was wondering about the same issues as yourself: now you can pass a **raml** query string param to supply the location of your RAML file. While developing, I do keep an open tab with a URL like [http://dev_server:api_console_port/?raml=http://dev_server:raml_file_port/project.raml](http://dev_server:api_console_port/?raml=http://dev_server:raml_file_port/project.raml) and refresh it on a regular basis when I make changes to the RAML file.

I find this more convenient than using the API Designer, since I don't need most of the functionality there, e.g. I code in Vim and don't use browser based editors, so this might be convenient for you as well.

I also agree that the unformatted JSON when there's an error is hard to use: a simple pretty print on that would *drastically* improve the UX while developing.

**Comment by jcenturion** [comment]
@DavidBiesack, @mgogov: We have already made a couple of improvements in the latest version in regards to handling errors when loading from a RAML file or parsing it.

- Errors when loading a RAML file

![screen shot 2015-03-10 at 4 19 23 pm](https://cloud.githubusercontent.com/assets/302314/6587469/df26cfc2-c741-11e4-877b-b41cae39d835.png)

- Errors when parsing a RAML

![screen shot 2015-03-10 at 4 18 00 pm](https://cloud.githubusercontent.com/assets/302314/6587471/e2d7228e-c741-11e4-9afe-2b9f34ee3dc4.png)

**Comment by sichvoge** [comment]
There is still things we can do better here. The Load from URL does not show the exact errors in the newest version and the small textbox does not get refreshed and mostly I need to refresh the page to remove errors.

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
