### ISSUE TITLE
OAuth 2.0 Client Credentials Supported?

### ISSUE THREAD

**Issue by lhallowes** [mulesoft/api-console#77]
We secure our api using OAuth 2.0 using client credentials but I can't get it to work using the 'Try It' functionality in api-console.

The RAML spec says that the authorization grants can be any of: code, token, owner or credentials but I get a javascript error when I try to use credentials that says the authStrategy is undefined. My javascript isnt amazing but the GRANTS array in the OAuth 2 section (https://github.com/mulesoft/api-console/blob/master/dist/scripts/app.js#L720) it only has code and token. If I use code or token I do not get the same js error.

Am I missing something or is client creds unsupported?

Thanks

**Comment by jcenturion** [comment]
@lhallowes: It should be working on the latest version. If not working let us know.

**Comment by robvanmieghem** [comment]
@jcenturion @sichvoge It does do a post on the access_token endpoint passing the `grant_type=client_credentials` and the scope as form parameters but not the client_id and client_secret it seems.

**Comment by ryan-slack-big** [comment]
As of Mule 3.8.3, it is trying to use basic auth instead of sending the credentials in the form data.

**Request Headers**
```
Accept:application/json, application/x-www-form-urlencoded
Accept-Encoding:gzip, deflate, br
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Authorization:Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Cache-Control:no-cache
Connection:keep-alive
Content-Length:36
Content-Type:application/x-www-form-urlencoded
Host:localhost:8082
Origin:https://localhost:8082
Pragma:no-cache
Referer:https://localhost:8082/console/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
```
**Form Data**
`scope=&grant_type=client_credentials`

**Comment by diegomontaner** [comment]
@ryan-slack-big I am seeing the same thing on mule enterprise runtime 3.8.2 in my local environment. Do you know if there was any progress on this? Did you manage to work around it?

Thanks!

**Comment by jarrodek** [comment]
This should work in v4 as described in OAuth spec. But because I can't find an endpoint to test it I can't tell for sure. 

@sichvoge can we arrange some test environment to test various OAuth 2 types?

**Comment by arashp** [comment]
Guys I am facing same issue in Try it for console using RESOURCE OWNER PASSWORD CREDENTIAL flow in oauth2 it is poping up the browser basic authentication and fails with 401 I put all info correctly on client_id, client_secret, username, password in Try It screen. I noticed it works when I use postman and post directly to the token endpoint as below:

token?grant_type=password&username=john&password=doe&client_id=e7aaf348-f08a-11e1-9237-96c6dd6a022f&client_secret=ee9acaa2-f08a-11e1-bc20-96c6dd6a022f

I believe the issue is Try it page is posting to oauth token endpoint Authorization:Basic instead of Authorization: Bearer. Please clarify if this is a known bug and if it is fixed? I am using Mule runtime

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
